[project]
name = "webtools-mcp"
version = "0.1.0"
description = "Web Search Tool for AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.12.0",
    "attrs==25.4.0",
    "babel==2.17.0",
    "certifi==2025.11.12",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "courlan==1.3.2",
    "cryptography==46.0.3",
    "dateparser==1.2.2",
    "h11==0.16.0",
    "htmldate==1.9.4",
    "httpcore==1.0.9",
    "httptools==0.7.1",
    "httpx==0.28.1",
    "httpx-sse==0.4.3",
    "idna==3.11",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.9.1",
    "jusText==3.0.2",
    "lxml==6.0.2",
    "lxml_html_clean==0.4.3",
    "mcp==1.25.0",
    "pycparser==2.23",
    "pydantic==2.12.5",
    "pydantic-settings==2.12.0",
    "pydantic_core==2.41.5",
    "PyJWT==2.10.1",
    "pypdf>=6.6.2",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "python-multipart==0.0.21",
    "pytz==2025.2",
    "PyYAML==6.0.3",
    "referencing==0.37.0",
    "regex==2025.11.3",
    "rpds-py==0.30.0",
    "six==1.17.0",
    "sse-starlette==3.0.4",
    "starlette==0.50.0",
    "tld==0.13.1",
    "trafilatura==2.0.0",
    "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
    "tzlocal==5.3.1",
    "urllib3==2.6.2",
    "uvicorn==0.38.0",
    "uvloop==0.22.1",
    "watchfiles==1.1.1",
    "websockets==15.0.1",
]

[project.optional-dependencies]
dev = [
    "coverage==7.10.6",
    "html-testRunner==1.2.1",
    "unittest-xml-reporting==3.2.0",
]

[project.scripts]
test = "webtools_server.scripts:run_tests"
coverage = "webtools_server.scripts:run_coverage"
test-html = "webtools_server.scripts:run_test_html"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["webtools_server"]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.uv]
package = true
